apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Venkatehrn/flux1/blob/main/my-chart/values.yaml
  ref:
    branch: main
